name: bus_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


 
  cupertino_icons: ^1.0.6
  firebase_core: ^2.31.0
  firebase_auth: ^4.19.5
  google_fonts: ^6.2.1
  flutter_native_splash: ^2.2.8
  smooth_page_indicator: ^1.1.0
  liquid_swipe: ^3.1.0



dev_dependencies:
  flutter_test:
    sdk: flutter


 
  flutter_lints: ^3.0.0

# flutter_native_splash-development.yaml
flutter_native_splash:
  color: "#ffffff"
  image: assets\images\splash_screen2.png
  branding: assets\images\books.png.png
  color_dark: "#121212"
  image_dark: assets\images\splash_screen1.png
  branding_dark: assets\images\books.png.png
  android_12:
    image: assets\images\splash_screen2.png
    icon_background_color: "#ffffff"
    image_dark: assets\images\splash_screen1.png
    icon_background_color_dark: "#121212"
  web: false
# flutter_native_splash-acceptance.yaml
# flutter_native_splash:
#   color: "#ffffff"
#   image: assets\images\splash_screen2.png
#   branding: assets\images\books.png.png
#   color_dark: "#121212"
#   image_dark: assets\images\splash_screen1.png
#   branding_dark: assets\images\books.png.png
#   android_12:
#     image: assets\images\splash_screen2.png
#     icon_background_color: "#ffffff"
#     image_dark: assets\images\splash_screen1.png
#     icon_background_color_dark: "#121212"
#   web: false


# flutter_native_splash-production.yaml
# flutter_native_splash:
#   color: "#42a5f5"
#   image: assets\images\splash_screen2.png
#   branding: assets\images\books.png.png
#   color_dark: "#042a49"
#   image_dark: assets\images\splash_screen1.png
#   branding_dark: assets/branding-development.png
#   android_12:
#     image: assets\images\splash_screen2.png
#     icon_background_color: "#111111"
#     image_dark: assets\images\splash_screen1.png
#     icon_background_color_dark: "#eeeeee"
#   web: false
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true



assets:
    assets/images/
    assets/images/splash_images/
    assets/images/on_boarding_images/
    assets/images/welcome_images/
